//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chainski_Crypter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chainski_Crypter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.IO;
        ///using System.Reflection;
        ///using System.Security.Cryptography;
        ///using System.Text;
        ///using System.Resources;
        ///using System.Runtime.InteropServices;
        ///using System.Windows.Forms;
        ///using System.Threading;
        ///
        ///[assembly: AssemblyTitle(&quot;#AssemblyProduct&quot;)]
        ///[assembly: AssemblyDescription(&quot;#AssemblyDescription&quot;)]
        ///[assembly: AssemblyCompany(&quot;#AssemblyProduct&quot;)]
        ///[assembly: AssemblyProduct(&quot;#AssemblyProduct&quot;)]
        ///[assembly: AssemblyCopyright(&quot;#AssemblyCopyright&quot;)]
        ///[assembly: AssemblyTrademark(&quot;#Assem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Loader {
            get {
                return ResourceManager.GetString("Loader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //#define install
        ///
        ///using System;
        ///using System.ComponentModel;
        ///using System.Diagnostics;
        ///using System.Runtime.InteropServices;
        ///using System.Security;
        ///using System.Security.AccessControl;
        ///using System.Security.Principal;
        ///using System.Resources;
        ///using System.Reflection;
        ///using System.IO;
        ///using System.Security.Cryptography;
        ///using System.Text;
        ///using System.Threading;
        ///using System.Windows.Forms;
        /// 
        ///namespace Stub
        ///{
        ///   public class Program
        ///    {
        ///       public void Run()
        ///        {
        ///#if install
        ///            Installer in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stub {
            get {
                return ResourceManager.GetString("Stub", resourceCulture);
            }
        }
    }
}
